(display "Joc de proves per la definció de funcions i constants")
(newline)

(display "Prova de la definicio d'una constant")
(newline)
(define PI 3.141592)
(display "El valor de PI es: ")
(display PI)
(newline)

(display "Prova de la definicio d'una funcio")
(newline)
(define (suma a b)
  (+ a b))
(display "El resultat de sumar 3 i 4 es: ")
(display (suma 3 4))
(newline)

(display "Prova d'una funcio recursiva")
(newline)
(define (factorial n)
  (if (= n 0)
      1
      (* n (factorial (- n 1)))))
(display "El factorial de 5 es: ")
(display (factorial 5))
(newline)

(display "Prova de definir un parametre global i despres canviar-li el valor")
(newline)
(define a 5)
(display "El valor de a es: ")
(display a)
(newline)
(display "Canviem el valor de a a 10")
(newline)
(define a 10)
(display "El nou valor de a es: ")
(display a)
(newline)

(display "Prova de definir una llista i operar amb les seves funcions")
(newline)
(define llista '(1, 2, 3, 4, 5))
(display "La llista es: ")
(display llista)
(newline)
(display "El primer element de la llista es: ")
(display (car llista))
(newline)
(display "Li afegim un element a la llista")
(newline)
(define llista (cons 0 llista))
(display "La nova llista es: ")
(display llista)
(newline)
