(display "Joc de proves pel let")
(newline)

(display "Prova basica del let")
(newline)
(let ((a 5)
      (b 3))
  (display "El valor de a es: ")
  (display a)
  (newline)
  (display "El valor de b es: ")
  (display b)
  (newline)
  (display "La suma de a i b es: ")
  (display (+ a b))
  (newline))

(display "Prova de let amb una funcio")

(define (sum a b)
  (+ a b))

(newline)
(let ((a 5)
      (b 3))
  (display "El valor de a es: ")
  (display a)
  (newline)
  (display "El valor de b es: ")
  (display b)
  (newline)
  (display "La suma de a i b es: ")
  (display (sum a b))
  (newline))

(display "Prova de tenir una variable global amb el mateix nom que una variable local")
(newline)
(define a 10)
(let ((a 5))
  (display "El valor de a es: ")
  (display a)
  (newline))
(display "El valor de la variable global a es: ")
(display a)
(newline)
